load 'Cz.mat';
% load '218.mat';
% Cz = double(data(:, 2));
N = size(Cz, 1);
Fs = 250;

filters = {
    struct( ...
        'filter', filter_4Hz, ...
        'f0', 1, ...
        'f1', 5 ...
    ), ...
    struct(  ...
        'filter', filter_7Hz, ...
        'f0', 5, ...
        'f1', 10 ...
    ), ...
    struct( ...
        'filter', filter_10Hz, ...
        'f0', 8, ...
        'f1', 13 ...
    ), ...
    struct( ...
        'filter', filter_14Hz, ...
        'f0', 11, ...
        'f1', 17 ...
    ), ...
    struct( ...
        'filter', filter_15Hz, ...
        'f0', 15, ...
        'f1', 80 ...
    ) ...
};
    
windowWidth = 1000;
stepWidth = 60;
for i = windowWidth : stepWidth : N
    start = i - windowWidth + 1;
    finish = i;
    window = Cz(start : finish);
    plot_psd(window, Fs, filters, sprintf('%g - %g', start/Fs, finish/Fs));
%     break;
end